//
//   Title:         SFBusinessDataConnectivity.INC
//
//   Description:   connectivity conditions for compiler
//
//   Created by:    Frank Huber
//
//   Copyright:     Frank Huber - The SoftwareFactory -
//                  Alberweilerstr. 1
//                  D-88433 Schemmerhofen
//
//                  http://www.thesoftwarefactory.de
//

{$DEFINE HASFIREDAC}
{$DEFINE HASIBX}


