//
//   Title:         SFBusinessDataConst
//
//   Description:   constants for specific business-datasets
//
//   Created by:    Frank Huber
//
//   Copyright:     Frank Huber - The SoftwareFactory -
//                  Alberweilerstr. 1
//                  D-88433 Schemmerhofen
//
//                  http://www.thesoftwarefactory.de
//
unit SFBusinessDataConst;

interface

const
  // messages
  SFBDSMSG_NOTININSERTEDIT          = 'not in insert or edit mode';
  SFBDSMSG_CLASSEXISTS              = 'a businessclass with name %s already exists';
  SFBDSMSG_FULLREFRESHWITHUPD       = 'FullRefresh not possible with not applied updates';
  SFBDSMSG_NOWRITEINMODE            = 'writing field is not possible in current mode';
  SFBDSMSG_MISSINGCONNECTOR         = 'no connector is defined';
  SFBDSMSG_NOSEARCHFIELDS           = 'no fields for where-condition';
  SFBDSMSG_INVALIDAUTOTYPE          = 'invalid type for autovalue';
  SFBDSMSG_CACHEDUPDWHENEDIT        = 'Setting CachedUpdates not possible in insert-/edit-mode';
  SFBDSMSG_INVALIDCONNECTION        = 'invalid type of connection';
  SFBDSMSG_COMMONCONNECTOR          = 'a common connector already exists';
  SFBDSMSG_INVALIDTRANSTYPE         = 'invalid type of transaction';
  SFBDSMSG_CONNECTIONMAPEXISTS      = 'a connectionmap for this type already exists';
  SFBDSMSG_NOCONNECTIONTYPE         = 'a connectiontype is required';
  SFBDSMSG_NOTRANSACTIONFORTYPE     = 'for the given connectiontype no transactions are possible';
  SFBDSMSG_TABLEREQUIRED            = 'for this action a tablename is required';
  SFBDSMSG_NAMEONAUTOGENPRMVAL      = 'you cannot set name for autogenerated paramvalue';
  SFBDSMSG_BUSINESSDATADEMOEXPIRED  = 'your demo from TSFBusinessData is expired';

implementation

end.
